import type { NextPage } from 'next'
import Head from 'next/head'









const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Hello world</h1>
            </main>

            <footer>
                <p>This is a footer</p>
            </footer>
        </div>
    )
}

export default Home
