import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main>
                <h1>Hello world</h1>
                <div>
                    <Link href={'/remount/static1'}>Static 1</Link>
                </div>
                <div>
                    <Link href={'/remount/static2'}>Static 2</Link>
                </div>
                <div>
                    <Link href={'/remount/static3'}>Static 3</Link>
                </div>
            </main>

            <footer>
                <p>This is a footer</p>
            </footer>
        </div>
    )
}

export default Home
